name: pull_request_coverage
description: This tool is designed to analyze the test coverage rate of a pull request, taking into consideration only the lines that have been changed.
repository: https://github.com/talesbarreto/pull_request_coverage
version: 2.1.0
topics:
 - ci
 - test
 - coverage
 - test-coverage

screenshots:
  - description: The output of the command `pull_request_coverage` in a terminal.
    path: screenshots/Screenshot_01.png

executables:
  pull_request_coverage:

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  args: ^2.4.2
  file: ^7.0.0
  glob: ^2.1.2
  yaml: ^3.1.2

dev_dependencies:
  test: ^1.24.4
  mocktail: ^0.3.0
  lints: ^2.1.1
